PANEL_HEIGHT  = 250
PANEL_WIDTH = 500
PANEL_FONT_SIZE = 10
PANEL_FONT_TYPE = "Comic Sans MS"

CARD_IMAGE_DEFAULT_FOLDER = "images"
CARD_IMAGE_DEFAULT_NAME = "default"
CARD_IMAGE_DEFAULT_EXTENSION = "jpg"

TITLE_ICON_FOLDER = "images"
TITLE_ICON_PREFIX = "media"
TITLE_ICON_EXTENSION = 'png'
TITLE_ICON_HEIGHT = 35

RATING_ICON_FOLDER = "images"
RATING_ICON_PREFIX = "rating" 
RATING_ICON_EXTENSION = "png"
RATING_ICON_FAVORITE_TAG = 'favorite'
RATING_ICON_NEW_TAG = 'new'
RATING_ICON_SIZE = 25

STORAGE_BACKGROUND_COLOR = "#b3d4c9"
COLLECTOR_BACKGROUND_COLOR = "#3f6b61"
RATE_BACKGROUND_COLOR = "#f7bb07"

ON = "on"
OFF = "off"