PANEL_HEIGHT  = "230"
PANEL_WIDTH = "500"
PANEL_FONT_SIZE = "14"

TITLE_ICON_FOLDER = "icons"
TITLE_ICON_PREFIX = "media"
TITLE_ICON_EXTENSION = 'png'
TITLE_ICON_HEIGHT = '35px'

RATING_ICON_FOLDER = "icons"
RATING_ICON_PREFIX = "rating" 
RATING_ICON_EXTENSION = "png"
RATING_ICON_FAVORITE_TAG = 'favorite'
RATING_ICON_NEW_TAG = 'new'

STORAGE_BACKGROUND_COLOR = "#b3d4c9"

COLLECTOR_BACKGROUND_COLOR = "#3f6b61"

